### PR TITLE
Apache client update for DataONE

### PR DESCRIPTION
**Pull request by ryscher**
Fixes the first issue on https://trello.com/c/uvOwJ7Lj --- allows bitstreams to be downloaded through the DataONE API using a URL like http://datadryad.org/mn/object/doi:10.5061/dryad.20/1/bitstream

Also removes some old entries in pom files that were already commented out.

### CODE REVIEW

**Comment by daisieh** [comment]
The downloaded bitstream (when I attach an actual assetstore to my VM) looks fine (it's a Word doc and opens correctly in Word), but is named `bitstream.dot`. Is that expected behavior?

**Comment by ryscher** [comment]
Are you using a command line tool? Some of them automatically name the download based on the URL. When I open the above link in a browser (using my VM instead of prod), I get a file named `Evo_22_Table S1.doc`.

**Comment by daisieh** [comment]
No, I was using Safari.

**Comment by daisieh** [comment]
I get a correctly-named file in Chrome, though. I'm going to chalk that up to a browser quirk. Otherwise, this is fine.

**Pull request merged**
