### PR TITLE
SWORD + BagIt package ingest

### PR DESCRIPTION
**Pull request by jar398**
This PR is for the Open Tree / Dryad handshake. Documentation here:

http://wiki.datadryad.org/Open_Tree_/_Dryad_handshake#Documentation

This breaks some of the payment-system tests, because new tests create Items that apparently don't play nice with it. I haven't looked into this problem yet.

This feature is not really finished (see doc about the 'claim' feature), but adding it to the code base should be harmless, other than the testing issue.

### CODE REVIEW

**Comment by jar398** [comment]
Well I don't understand this at all. Looking at the travis log I don't even see the bagit tests being run at all. If that's the case I don't see how I could have possibly broken the payment-system tests. And if it's not the case (i.e. the bagit tests are running), the error looks to be a null pointer doing getCurrentUser(), which equally makes no sense to me. I'd really appreciate someone else taking a look at this.

**Comment by jar398** [comment]
FYI, to add these commits to Dryad without enabling the sword service - i.e. to make the new code completely inert, so that there's no threat to the rest of the system - just undo the one-line changes to these files:
dspace/etc/server/production/server.xml
dspace/etc/server/server.xml-fragment
The sword service could then be turned on at any time, like once the authentication regime is worked out. (Current authentication is by username and password.)

**Comment by ryscher** [comment]
This change is no longer relevant, since we will be using the SWORD capabilities of the new Dash/Dryad system.

**Comment by jar398** [comment]
I had been wondering!

**Pull request closed without merging**
