### PR TITLE
Curator wkly reports

### PR DESCRIPTION
**Pull request by dfagandryad**
First iteration of Weekly reports. Adding CuratorWeeklyReport.java and updating curate.cfg. Report is run as follows:  /opt/dryad/bin/dspace curate -v -t weeklyreport -i 10255/2 -r - >~/temp/weeklyreport.csv

### CODE REVIEW

**Comment by daisieh** [comment]
@dfagandryad: what should the result of the report be? When I compile it and run it on my VM, I get a lot of `ERROR org.dspace.curate.CuratorWeeklyReport @ Skipping -- Object has no prism.publicationName available` messages that seem to relate to dataset objects, but no output that relates to any package objects at all.

```
Adding task: weeklyreport
Starting curation
Curating id: 10255/2
handle, packageDOI, articleDOI, journal, journalAllowsEmbargo, journalAllowsReview, embargoType, embargoDate, manuscriptNum, wentThroughReview, dateAccessioned, date
Issued
"[no handle found]", "[no package DOI found]", "[no article DOI found]", "[no journal found]", false, false, none, , null, false, "[unknown]","[unknown]"
2015-11-12 01:24:13,416 ERROR org.dspace.curate.CuratorWeeklyReport @ Skipping -- Object has no prism.publicationName available 10255/dryad.7874
........a bunch of similar messages......
Ending curation. Elapsed time: 959
```

**Comment by daisieh** [comment]
From a code perspective, if this is pretty much exactly the same code as DataPackageStats.java, wouldn't it be better to inherit from that class instead and make modifications as necessary? I really hate it when we have multiple versions of exactly the same code.

**Comment by dfagandryad** [comment]
Following is a sample output file. It is a comma-separated .csv file that can be imported into a spreadsheet.
vagrant@precise64:~/dryad-repo$ cat ~/temp/weeklyreport.csv

Adding task: weeklyreport
Starting curation
Curating id: 10255/3
handle, packageDOI, articleDOI, journal, journalAllowsEmbargo, journalAllowsReview, embargoType, embargoDate, manuscriptNum, wentThroughReview, dateAccessioned, dateIssued
"[no handle found]","[no package DOI found]","[no article DOI found]",[no journal found],false,false,none,,null,false,"[unknown]","[unknown]"
10255/dryad.7873,doi:10.5072/FK2dryad.7d152,"[no article DOI found]",BMC Ecology,true,true,none,,null,true,2015-04-24T01:20:53Z,2015-04-24
10255/dryad.7875,doi:10.5072/FK2dryad.gf34p,"[no article DOI found]",Heredity,true,false,none,,null,true,2015-04-24T01:23:56Z,2015-04-24
10255/dryad.7877,doi:10.5072/FK2dryad.29vg8,"[no article DOI found]",Dryad Testing Journal,true,true,untilArticleAppears,2015-04-29,null,true,2015-04-24T01:24:56Z,2015-04-24
10255/dryad.7879,doi:10.5072/FK2dryad.k143c,"[no article DOI found]",Dryad Testing Journal,true,true,oneyear,9999-01-01,null,true,2015-04-24T01:26:05Z,2015-04-24
10255/dryad.7881,doi:10.5072/FK2dryad.h665h,"[no article DOI found]",Dryad Testing Journal,true,true,untilArticleAppears,9999-01-01,null,true,2015-04-24T01:27:15Z,2015-04-24
10255/dryad.7885,doi:10.5072/FK2dryad.66ds3,"[no article DOI found]",Dryad Testing Journal,true,true,oneyear,9999-01-01,null,true,2015-04-24T01:32:19Z,2015-04-24
10255/dryad.7887,doi:10.5072/FK2dryad.p3m5k,"[no article DOI found]",Dryad Testing Journal,true,true,untilArticleAppears,9999-01-01,null,true,2015-04-24T01:47:49Z,2015-04-24
10255/dryad.7889,doi:10.5072/FK2dryad.cq5b9,doi:1234567890,Dryad Testing Journal,true,true,untilArticleAppears,9999-01-01,null,true,2015-04-24T16:51:38Z,2015-01-01
10255/dryad.7891,doi:10.5072/FK2dryad.1j031,"[no article DOI found]",Dryad Testing Journal,true,true,untilArticleAppears,2015-04-25,null,true,2015-04-24T17:48:09Z,2015-04-24
10255/dryad.7893,doi:10.5072/FK2dryad.05jv8,"[no article DOI found]",Dryad Testing Journal,true,true,custom,9999-01-01,null,true,2015-04-24T21:52:02Z,2015-04-24
10255/dryad.7895,doi:10.5072/FK2dryad.v1v2b,"[no article DOI found]",Evidence-based Preclinical Medicine,true,true,none,,null,true,2015-08-19T04:00:00Z,2015-08-19
Ending curation. Elapsed time: 1742

**Comment by daisieh** [comment]
I'm still getting no results when I run it on my VM.

**Comment by ryscher** [comment]
Closing this, because it seems unlikely that we will return to it before fully transitioning to the new system.

**Pull request closed without merging**
