### PR TITLE
Curator note redux

### PR DESCRIPTION
**Pull request by daisieh**
Added a new dryad metadata field, curatorNotePublic, and displayed that one instead at the top of the item summary page.

### CODE REVIEW

**Comment by daisieh** [comment]
@rnathanday, would you mind doing a quick verify on this? It's exactly the same as the one you reviewed last week, but with a new metadata field.

**Comment by daisieh** [comment]
Well, maybe you can help me figure out why the Travis build failed...?

**Comment by ghost** [comment]
The Travis tests failed in `org.dspace.content.MetadataSchemaTest` here:

```
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.629 sec <<< FAILURE!
testFind_Context_String(org.dspace.content.MetadataSchemaTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: testFind_Context_String 0
Expected: not null
     got: null
    at org.dspace.content.MetadataSchemaTest.testFind_Context_String(MetadataSchemaTest.java:386)
```

which is in `dspace-api/src/test/java/org/dspace/content/MetadataSchemaTest.java`.

I did not get the same failure when I ran the build/test script on my VM, and I do not see what would cause a failure looking at the test.

**Comment by dleehr** [comment]
This failure comes up pretty regularly on travis. I haven't found a good reason why it fails - and sometimes it doesn't - restarting the build often completes successfully.

Some thoughts - maybe it's a  certain pool of travis servers that fail, or maybe an earlier database state causes this to fail?

**Comment by ghost** [comment]
#### Code Review Checklist
- [x] Read through the code to ensure it is:
- [x] Legible
- [ ] Well-commented
- [x] Free of any "code smells"
- [ ] Ensure the associated documentation is up to date.
- [x] Compile it on your local machine and test the new functionality.
- [ ] Verify that the change is accompanied by adequate testing code. Verify that the code passes the tests.

This update tests out in the browser using the same steps as the predux:
- checkout branch, deploy, start app
- for existing data package, go to Edit Item page, then Item Metadata tab
- add new metadata item for package, using dryad.curatorNotePublic
- navigate to package page and confirm that the public curator note shows in a panel under data package title and that the curatorNote does not

**Comment by ghost** [comment]
A restart also failed, but since this passed locally and this test is flakey on Travis, I'm going to merge.

**Pull request merged**
