### PR TITLE
Fixes for ORCID on Describe Publication page

### PR DESCRIPTION
**Pull request by daisieh**
This refactoring allows different icons to be displayed for different authority controls. It also places the "Look up author in the ORCID registry" button before manual author add.

### CODE REVIEW

**Comment by daisieh** [comment]
These new changes address suggestions from https://trello.com/c/TzGovks2/352-add-authors-page. They have been deployed on dev and approved by Elizabeth and Todd.

**Comment by daisieh** [comment]
I added an extra fix to make sure that the authority/confidence set for publication authors is propagated to the datasets.

**Comment by daisieh** [comment]
I just deployed these last two changes to dev and they are working there.

**Comment by ryscher** [comment]
The button "Lookup author in the ORCID registry" is slightly offset, to the right. We should align it with the surrounding text.

**Comment by ryscher** [comment]
When a name is connected to ORCID, the Edit Metadata screen has "Lookup" buttons that look up the name in the LoC Name Authority instead of ORCID. Does stock DSpace do this?

**Comment by ryscher** [comment]
The confidence value assigned to an author name is 600 whether the name is looked up in ORCID or entered in the text boxes. Should these be the same?

**Comment by ryscher** [comment]
All code looks good, and the UI is much better than before, so we can merge this and fix the above issues later.

**Pull request merged**
