### PR TITLE
moving common methods into one parent class

### PR DESCRIPTION
**Pull request by daisieh**
I consolidated the common methods between DescribeDatasetStep and DescribePublicationStep into a parent class, DescribeStep. The remaining methods are still largely similar, but this is as much as I can do without actually going into detailed testing.

### CODE REVIEW

**Comment by daisieh** [comment]
oops, accidentally deleted an active branch!

**Comment by ryscher** [comment]
Doesn't compile.... missing imports for List, Calendar, etc.

**Comment by daisieh** [comment]
This isn't urgent and is probably too old to fix easily. I'll take it off the docket for now and fix it up when I have time.

**Comment by daisieh** [comment]
@ryscher, this should be good for code review now.

**Comment by ryscher** [comment]
Looks good. Tested ok on vm.

**Pull request merged**
