### PR TITLE
disable Dspace unit tests

### PR DESCRIPTION
**Pull request by daisieh**
We don’t touch these classes and they randomly break Travis.

### CODE REVIEW

**Comment by daisieh** [comment]
@ryscher, should I disable just the one test that usually fails on Travis, ItemTest?

**Comment by ryscher** [comment]
I don't think this is necessary any longer. The tests seem to be passing now.

**Comment by daisieh** [comment]
can we at least turn off the reporting of deprecated classes? I commented out the exclusion of tests.

**Comment by daisieh** [comment]
It's ironic that Travis failed on one of the tests that would've been commented out.

**Pull request merged**
