### PR TITLE
Jrnl cover bone and joint

### PR DESCRIPTION
**Pull request by dfagandryad**
Adding cover images for the Bone & Joint journals (BJJ, BJR and BJ360). Added files and updated DryadItemSummary.xsl and Mirage.xsl.

### CODE REVIEW

**Comment by daisieh** [comment]
This won't work as is; the code changes need to use `&amp;` instead of bare ampersands.

**Comment by daisieh** [comment]
I can't figure out how to assign this back to @dfagandryad, so hopefully she sees this comment. If this needs to be merged and deployed before next Wednesday, I can redeploy sometime this weekend after these changes have been made.

**Comment by dfagandryad** [comment]
Thanks, Daisie. I wondered about that goofy ampersand. Ordinarily I would
have used the &amp; in regular old HTML, but I wasn't sure how these files
would be used to create the page display. I'm still not sure where the
ampersand is appropriate and where it should be &amp; instead. It is late
so I will revisit this in the morning when I will be less likely to screw
it up.

Thanks, again...

Debra

On Thu, Jul 23, 2015 at 10:42 PM, Daisie Huang notifications@github.com
wrote:

> I can't figure out how to assign this back to @dfagandryad
> https://github.com/dfagandryad, so hopefully she sees this comment. If
> this needs to be merged and deployed before next Wednesday, I can redeploy
> sometime this weekend after these changes have been made.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datadryad/dryad-repo/pull/961#issuecomment-124297239.

## 

Debra Fagan

Curation and Technical Specialist
Dryad Digital Repository
dfagan@datadryad.org

**Comment by daisieh** [comment]
This works now, merging.

**Pull request merged**
