### PR TITLE
Static init in JournalConceptDatabase class causes problems

### PR DESCRIPTION
**Pull request by daisieh**
For some reason, trying to initialize the fields dynamically doesn’t work. I’m not sure that this is the best solution, but it is the one currently deployed on prod.

### CODE REVIEW

**Comment by ryscher** [comment]
Hmmmm. This approach is almost certain to cause problems as Dryad is installed on different machines and the specific IDs change. If the static initialization is a problem, could we initialize these elsewhere? In the constructor or the method where they are used?

**Comment by daisieh** [comment]
I forgot that I'd cached the MetadataField values in the runtime, so retrieving them in the instance method won't incur more database hits.

**Comment by daisieh** [comment]
For some reason, the REST API webapp doesn't always instantiate the MetadataField class in time, so I had to introduce a manual instantiation. It should be fine now. Test the REST API, APU, journal submit email checker, and regular UI to be sure everything works.

**Comment by ryscher** [comment]
Looks good, tested on VM.

**Pull request merged**
