### PR TITLE
Limit REST API results

### PR DESCRIPTION
**Pull request by daisieh**
Sets a default limit of 1000 records for manuscript GET calls, but allows a query parameter to specify a different number.

### CODE REVIEW

**Comment by daisieh** [comment]
I added the search-on-single-term thing into this PR as well. Test by running with `search=Smith` or whatever.

**Comment by ryscher** [comment]
All code changes look good.

**Comment by ryscher** [comment]
All functionality tests out.

**Comment by ryscher** [comment]
This is ready to merge, but let's change the "results" parameter to "count" in order to mirror the DataONE API.

**Comment by daisieh** [comment]
This works fine with the parameter changed to "count", so I am merging.

**Pull request merged**
