### PR TITLE
Datacite updates

### PR DESCRIPTION
**Pull request by daisieh**
Updates crosswalks to 4.0 schema, adds orcids and versioning.

### CODE REVIEW

**Comment by daisieh** [comment]
Run the crosswalks against a versioned file and package and make sure it validates.
Try http://datadryad.org/resource/doi:10.5061/dryad.sc286.3/11.3

Run the crosswalks against a package with ORCIDS and make sure it validates.
Try http://datadryad.org/resource/doi:10.5061/dryad.nj5h5

**Comment by ryscher** [comment]
- Adds ORCIDs correctly.

**Comment by ryscher** [comment]
- Versioning works correctly for the listed example, but does *not* work for doi:10.5061/dryad.12 -- it looks like the version detection is based on a period followed by numbers, which is not always a version number. It would be better to strip out the "dryad." and see whether the remaining part contains a period.

**Comment by daisieh** [comment]
Okay, it should work now. However, it's hard to check metadata for data files right now because there seems to be something wrong with accessing their mets.xml.

**Comment by daisieh** [comment]
@ryscher I've added the fix to the ResourceIdentifierController that fixes the file mets.xml thing as well. Please verify those before merging.

**Comment by ryscher** [comment]
Updates look good. Tested on VM.

**Pull request merged**
