### PR TITLE
Show README and other file information in submission overview

### PR DESCRIPTION
**Pull request by daisieh**
Revamps the file listing in submission overview. 

Fixes https://trello.com/c/x4gAAi9b/623-display-readmes-on-review-submission-page-in-submission-system

### CODE REVIEW

**Comment by ryscher** [comment]
When I upload a readme, I get the following error. Not sure whether this is interacting with the httpclient changes....

```
java.lang.IllegalStateException: Socket not created by this factory
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:843)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1422)
	at org.dspace.storage.bitstore.BitstreamStorageManager.store(BitstreamStorageManager.java:381)

```

**Comment by daisieh** [comment]
Did you switch your assetstore back to your test one?

**Comment by ryscher** [comment]
yes, and I started a new deposit.

**Comment by daisieh** [comment]
Well, I didn't test it after we added the httpclient changes, so perhaps that is interacting.

**Comment by daisieh** [comment]
I tested the httpclient fix alone without this one, and it causes this problem too, so I reverted that PR #1423

**Comment by ryscher** [comment]
Retested without httpclient changes and this works fine.

**Pull request merged**
