### PR TITLE
Submission overview redesign

### PR DESCRIPTION
**Pull request by daisieh**
Cleaned up submission overview to look more like the planned review overview. Made the errors associated with non-verified files and no files more prominent.

### CODE REVIEW

**Comment by daisieh** [comment]
@ryscher I've fixed the lost button on the curator edit page. This should be ready for review now.

**Comment by ryscher** [comment]
Not sure whether it's related to this PR or other recent updates: 
1. add a link to an external file identifier (e.g., Genbank)
2. on the submission overview page, hit Edit for this file identifier
3. on the file editing page, hit Cancel
4. The external file identifier will be (incorrectly) deleted from the package

**Comment by ryscher** [comment]
Otherwise, looks good and tests fine.

**Comment by ryscher** [comment]
Works as expected.

**Pull request merged**
