### PR TITLE
Remove legacy files that are now generated by the dryad-linkout-tool

### PR DESCRIPTION
**Pull request by ryscher**
The NESCent address no longer works for wiki content.

### CODE REVIEW

**Comment by daisieh** [comment]
I have no idea how to test this.

**Comment by ryscher** [comment]
Unfortunately, the only way to test it is to put it in place. This file is read and used by the NCBI LinkOut system, and I don't believe they have a test server.

**Comment by ryscher** [comment]
Ugh, nevermind. This entire directory is not supposed to be here. It is a legacy from an old version of the dryad-linkout-tool.

**Comment by daisieh** [comment]
Sure, this seems to build fine.

**Pull request merged**
