### PR TITLE
DryadLab theme and custom pages (work in progress)

### PR DESCRIPTION
**Pull request by jimallman**
After wrangling for quite awhile to figure out how to populate my test instance of Dryad (using the recommended VM), I'm moving forward with test pages for DryadLab that use static/dummy data.

Given the 325(!) changed files here, it's likely that I haven't set up this pull request correctly. Please advise and I'll make corrections!

### CODE REVIEW

**Comment by jimallman** [comment]
Argh, I thought merging `datadryad:dryad-master` into mine would simplify this PR. Not so much... now there are 475 changed files. What's the standard procedure?

**Comment by jimallman** [comment]
> This might be easier to debug in future if you broke this out into nested conditionals...

Hi, @daisieh! Which files/commits are you referring to here?

> yes, some of the code could stand to be refactored.

@mdiggory, can you be more specific? I'm finding DSpace a bit overwhelming at the moment, so I'm trying to make these changes as simply as possible, without creating a mess.

**Comment by daisieh** [comment]
Hi @jimallman! I think those line notes came along with another branch/PR somehow. I remember making that comment awhile back for an Atmire PR or something.

**Comment by daisieh** [comment]
@jimallman: did you fast-forward your dryad-master branch before making the PR? I think that your fork's branch might be very far behind, and you might want to ff it before adding your changes.

**Comment by jimallman** [comment]
I'm closing this PR in favor of the rebased branch in #938. I believe that one will offer a cleaner history, and it is free of the entangled comments above.

**Pull request closed without merging**
