### PR TITLE
DPC change 2016

### PR DESCRIPTION
**Pull request by ryscher**
This collects all changes associated with the 2016 update to DPCs. 

This PR should be merged and deployed early on the morning of January 5, 2016.

### CODE REVIEW

**Comment by ryscher** [comment]
Included so far:
- Change of basic price
- New static pages for Terms of Service and payment plans
- Removal of the fee for non-integrated journals

**Comment by ryscher** [comment]
Now includes all changes to the main website pages.

**Comment by ryscher** [comment]
Some notes on the testing process:
- Submit stuff, check the prices. Hopefully they're all correct. (I didn't include a script, since I prefer you test things I haven't already thought of.)
- Look at the prices (including multiple currencies) on the static pages /payment, /paymentPlans, and /journalLookup
- Don't worry about the alternate currencies in the actual submission system. It currently only supports USD.

**Comment by daisieh** [comment]
Code looks fine.
- I checked the static pages and played with the currency conversions.
- I submitted packages for integrated and non-integrated journals and verified they were all $120.
- I tweaked the file sizes of files to 22GB, 2.2GB, and 50GB: all had the correct large file surcharge ($50, $0, and $150 respectively.)

I think this is okay to merge.

**Pull request merged**
