### PR TITLE
Embargo default should be "none"

### PR DESCRIPTION
**Pull request by daisieh**
This was an exceedingly easy fix (but I still tested it on my VM).

Fixes https://trello.com/c/q7BmUSvG

### CODE REVIEW

**Comment by ryscher** [comment]
This works for integrated journals, but for non-integrated journals, there is no "none" option. So the default will (incorrectly) go to 1 year.

**Comment by daisieh** [comment]
Are you sure that's how it works? I don't see anything in that method that says not to render that option if the journal isn't integrated.

**Comment by daisieh** [comment]
And as far as I can tell, you get the "publish immediately" option whether or not the journal is integrated.

**Comment by daisieh** [comment]
On my test machine, non-integrated journals also get the "publish immediately" option. Are they not supposed to?

**Comment by elizabethdryad** [comment]
It does seem to be true that "Publish immediately" is not an option for non-integrated journals. This is probably because non-int journals use pub blackout by default, so the files wouldn't ever be published before the article appears anyway (except in rare cases). So, I guess the options need to stay as-is for non-int journals.
screen shot 2017-06-26 at 5 27 50 pm

**Comment by elizabethdryad** [comment]
Erin made me realize -- I think the difference here is whether or not a journal uses blackout? Some integrated journals do, in which case the "Publish immediately" option wouldn't make sense. So, embargo default should be "publish immediately" only for integrated journals that do not use blackout. Other should stay as-is. (Sorry)

**Comment by daisieh** [comment]
Okay, this should behave properly now.

**Comment by ryscher** [comment]
I don't understand this. When blackout = false, this works correctly. But when blackout = true, it incorrectly defaults the embargo to one year. I've checked over the code again and again, and it looks right.

**Comment by ryscher** [comment]
Never mind.... my git repository was messed up... probably still had a merge with the previous version of this PR, so it was getting the wrong copy of the updates.

**Comment by ryscher** [comment]
Ok, now tests fine.

**Pull request merged**
