### PR TITLE
Siteupdates

### PR DESCRIPTION
**Pull request by dfagandryad**
Rename ByLaws2016.pdf to DryadByLaws.pdf and update class dates for board members in organization.xhtml.

### CODE REVIEW

**Comment by daisieh** [comment]
@dfagandryad Don't you need to change the file name in the link on membershipOverview.xhtml?

**Comment by dfagandryad** [comment]
Ordinarily, the file name in the link on membershipOverview.xhtml would need to be changed. However, that link is currently broken. Without the updates in this PR, the link points to DryadByLaws.pdf, but the actual filename is ByLaws2016.pdf. This PR leaves the link in membershipOverview.xhtml pointing to DryadByLaws.pdf and renames the file to DryadByLaws.pdf so the link should no longer be broken.

**Comment by daisieh** [comment]
Ah! I'm sorry, I got it backwards. This looks fine.

**Comment by dfagandryad** [comment]
No worries! Thanks, Daisie!

**Pull request merged**
