### PR TITLE
atmire-2487 fix version identification so it does not break building ind...

### PR DESCRIPTION
**Pull request by mdiggory**
...ividual modules

### CODE REVIEW

**Comment by daisieh** [comment]
How should I test this?

**Comment by daisieh** [comment]
I will test by trying to build journal landing page module and make sure that it doesn't break during normal build.

**Comment by mdiggory** [comment]
The build passing the Travis tests should be sufficient, it a very minor
change in the version attached to the artifact and used elsewhere in the
build.

On Wed, Apr 15, 2015 at 1:28 PM, Daisie Huang notifications@github.com
wrote:

> I will test by trying to build journal landing page module and make sure
> that it doesn't break during normal build.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datadryad/dryad-repo/pull/893#issuecomment-93558480.

## 

Mark R. Diggory

**Comment by daisieh** [comment]
Okay...I guess this is okay then? Merging.

**Pull request merged**
