### PR TITLE
Changed help text for bitstream descriptions

### PR DESCRIPTION
**Pull request by ryscher**
This is a fix for https://trello.com/c/UwXpMSi1

### CODE REVIEW

**Comment by ryscher** [comment]
@rnathanday I assigned this to you a while ago, but I guess I forgot to notify you...

**Comment by ghost** [comment]
@ryscher I don't have any record of an email from Github about the assignment, and I am not in the habit of checking the pull request page. Looking into it now -- thanks for the ping

**Comment by ghost** [comment]
I took the following steps 
1. checked out this branch, deployed, and started the webapp
2. selected a published package
3. selected "Edit this item" from the user menu
4. selected "Item Bitstreams" tab
5. clicked "upload a new bitstream" link
6. below Description, the original text still appears

Based on my understanding, this commit should have updated that text. Since it did not, I am assigning it back as faulty.
In investigating whether I was looking at the right page, I noticed that the "Optionally, provide a brief ..." string occurs in a number of messages.xml files.

**Comment by ryscher** [comment]
(I moved this into a new pull request, #766. This one is being closed.)

**Pull request closed without merging**
