### PR TITLE
Migrate provenances

### PR DESCRIPTION
**Pull request by daisieh**
Test by migrating some packages and see that the provenances get added correctly as curation activity, and that the current identifier state (as specified in the dataset’s curationStatus) is correct.

### CODE REVIEW

**Comment by ryscher** [comment]
Timestamps for some items are incorrect... see first two items in screenshot. These items are going into the DB as a date with no time (even though the specific time is in the provenance entry). And somewhere along the way, there is a time zone conversion, which results in the 16:00 instead of 00:00. 
screenshot 2018-12-12 13 24 46

**Comment by ryscher** [comment]
In another test example, an item was returned to the author, resubmitted by the author, and subsequently approved by the curator. Then the item was migrated to New Dryad. The migrated item has an incorrect status of "Author Action Required", presumably due to the incorrect timestamps. (https://dryad-dev.cdlib.org/stash/ds_admin/activity_log/694?utf8=%E2%9C%93)

**Comment by daisieh** [comment]
Damn, I thought that the timestamps wouldn't be a big deal, so I just left them out. I've added the time to the regex group now.

**Comment by ryscher** [comment]
Works great now!

**Pull request merged**
