### PR TITLE
atmire-2294- bug fix for journal/manuscript prepopulation.

### PR DESCRIPTION
**Pull request by mdiggory**
Corrections to journal prepopulation. 

1.) dropdown list was not getting populated correctly. 
2.) The identifier was switched to the full name of the journal instead of the short ID, this was corrected.

### CODE REVIEW

**Comment by daisieh** [comment]
I tried to pull this onto my VM.

I added a fake journal metadata file for RSPB/RSPB-2015-xxxx.xml and tried to use http://localhost:9999/submit?journalID=RSPB&manu=RSPB-2015-xxxx to get to the submission page.

I got a weird screen and this error in the dspace.log:
`2015-03-20 23:21:07,196 DEBUG org.dspace.app.xmlui.aspect.submission.submit.PublicationCompletedAction @ Publication completed action workspace ID: -1`

screen shot 2015-03-20 at 4 19 42 pm

**Comment by mdiggory** [comment]
Looks like your missing the collection handle for the DataPackage
collection.

Regards,
Mark

**Comment by daisieh** [comment]
Where am I missing it?

**Comment by mdiggory** [comment]
In the path /handle/10255/3/submit?....

**Comment by daisieh** [comment]
But the link I showed, `http://localhost:9999/submit?journalID=RSPB&manu=RSPB-2015-xxxx`, is the EXACT FORMAT that we always use for that journal's prepopulated manuscripts. We don't usually have to put any extra information into the URL.

**Comment by daisieh** [comment]
@mdiggory, can you tell me how to verify that this change does what you think it does?

**Comment by mdiggory** [comment]
the production server redirects/forwards /submit to the package collection

**Comment by daisieh** [comment]
So, where would I put this extra parameter in the URL to test it on my VM?

**Comment by mdiggory** [comment]
http://localhost:9999/handle/10255/3/submit?journalID=RSPB&manu=RSPB-2015-xxxx

**Comment by daisieh** [comment]
Okay. If I do that, the dropdown and identifier are populated correctly. The next page doesn't populate the metadata from the article, but that is a different bug.

**Comment by mdiggory** [comment]
Additional fixes have been provided to populate metadata.

On Fri, Mar 20, 2015 at 4:57 PM, Daisie Huang notifications@github.com
wrote:

> Okay. If I do that, the dropdown and identifier are populated correctly.
> The next page doesn't populate the metadata from the article, but that is a
> different bug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datadryad/dryad-repo/pull/892#issuecomment-84197727.

## 

Mark R. Diggory

**Comment by daisieh** [comment]
Okay. I tested this on my VM in the following way:
- I started a new submission
- I chose that it was "In preparation or in review"
- I noted that the journal dropdown menu is available again. I chose Mol Ecol Resources because I have a fake journal metadata file for a manuscript from them on my VM.
- I entered the MS number of that fake metadata file
- I noted that the next screen prepopulated the fields with the correct metadata.

However, the following test fails:
- I started a new submission
- I chose that it was "Published"
- I entered "test" or "MolEcol" in the journal name dialog box, both of which are valid short names in DryadJournalSubmission.testing.properties.
- At the next screen, the Journal name box is not autofilled with the full journal name instead of the short name, and, in the case of journal "test," a journal set to have a paid subscription, I noted that the payment sidebar did not indicate that the submission was paid for.

**Comment by mdiggory** [comment]
These journal short ID are not to be used in the form fields, they can only be applied from the request parameter. Are you getting a matching results in the journal name box?

Likewise, the test properties are not loaded into the EAC Scheme

**Comment by daisieh** [comment]
The test as I described it had always worked on Dryad before, and still works this way on dev.datadryad.org.

If I type in the full name in the box on the first submission page, the second page responds as expected, with the little green thumbs-up. However, I can't edit the field on the second page, even though it looks editable. These are all new behaviors that I was not expecting to be different.

**Comment by mdiggory** [comment]
The form for the journal in the describe step was intentionally disabled
some time ago, the journal must only be selected in the select publication
step.

Can you con confirm on your installation if the concepts loaded in journal
scheme are from the DryadJournalSubmission.testing.properties or
DryadJournalSubmission.properties?

**Comment by daisieh** [comment]
If it is not enabled, it should not look like a fillable text box. If it's been disabled and has been looking like an editable text box for some time, then that is a bug that has existed for some time.

My VM is using DryadJournalSubmission.testing.properties. If I enter "Dryad Testing Journal" in the select-publication step, a journal that only exists in DryadJournalSubmission.testing.properties, I get the correct paid subscription behavior on the describe-publication step.

**Comment by daisieh** [comment]
I confirmed with @ryscher that the behavior as it currently stands is the correct behavior, so I guess we can go ahead and merge this, but I will discuss the UI experience with the curators soon and work on behavior fixes in a different branch.

**Comment by mdiggory** [comment]
Any requests for new adjustments to the UI style and/behavior of the describe step can be handled as new tickets in our issue tracker. We will be glad to work on them.

At this time the Accepted > Journal Select is an Open Taxonomy, meaning that new values that do not match existing Journals will later be used to create new Journal Concepts in the EAC when the  DataPackage is archived into the repository.

From your feedback and a code review, it is true that the new EAC Authority Control is matching on fewer of the data fields than the original Solr Authority Control provided. The search field is configured in a dspace.cfg property as follows:

solrauthority.searchfieldtype = full-text

Looking over the solr authority documents, full-text is currently populated with only the Concept "value", (this is the Journal name). We may expand on the fields being indexed such that additional data such as metadata, can be matched on during term completion. The following is an example Solr record that shows that only the value is indexed into full-text. If additional fields are desired, we can work out a strategy to have them added.

image

It may be discussed within our regular call if EAC Solr search should be extended.

**Pull request merged**
