### PR TITLE
Semicolons or commas can be used.

### PR DESCRIPTION
**Pull request by daisieh**

### CODE REVIEW

**Comment by daisieh** [comment]
You should be able to use either semicolons or commas to separate lists of keywords, taxonomic names, geographic areas, or geologic timespans now.

**Comment by ryscher** [comment]
Looks good. Tests fine on data package pages, but semicolons still don't work on data file pages.

**Comment by daisieh** [comment]
OH MY GOD why are these repeated TWICE on this form. Fixing.

**Comment by daisieh** [comment]
There were so many inconsistencies that I can't believe they were never caught before. It should be better now, @ryscher .

**Comment by ryscher** [comment]
Updates test fine.

**Pull request merged**
