### PR TITLE
Update ms metadata

### PR DESCRIPTION
**Pull request by daisieh**
Fixes some issues in https://trello.com/c/BuiLN7ei/342-clean-up-issues-with-plos-integration.

### CODE REVIEW

**Comment by daisieh** [comment]
This change makes ManuscriptMetadataSynchronizationHandler use the same mechanism in ApproveRejectReviewItem as DryadEmailSubmission and ManuscriptReviewStatusChangeHandler. It also moves some metadata-updating features from ManuscriptMetadataSynchronizationHandler into ApproveRejectReviewItem, so that all three of the aforementioned classes do the same thing.

**Comment by daisieh** [comment]
To test, paste the following in a JSON file:

```
{"abstract":"Some stuff happened","dataAvailabilityStatement":null,"title":"A very interesting paper","status":"submitted","dataReviewURL":null,"manuscriptId":"PCOMPBIOL-D-11-00042","publicationDOI":null,"publicationDate":null, "authors":{"author":[{"givenNames":"John","familyName":"Smith"}]},"keywords":["more","this","that","else"]}
```

Then, using different values of status (submitted, then make a matching package), POST and then PUT the JSON as you move it to Accepted and then change metadata values, PUTting the new JSON through each time. You should see the data change for the package as well.

**Comment by ryscher** [comment]
Looks good. Yay, code consolidation!

**Comment by ryscher** [comment]
Changes look good. Merging.

**Pull request merged**
