### PR TITLE
Read Publication_DOI from manuscript metadata if present

### PR DESCRIPTION
**Pull request by dleehr**
Fixes **Read Publication DOI from XML during submission process** in [Trello 253](https://trello.com/c/dzMyczVd)

### CODE REVIEW

**Comment by daisieh** [comment]
#### Code Review Checklist
- [x] Read through the code to ensure it is:
- [x] Legible
- [x] Well-commented
- [x] Free of any "code smells"
- [x] Ensure the associated documentation is up to date.
- [x] Compile it on your local machine and test the new functionality.
- [x] Verify that the change is accompanied by adequate testing code. Verify that the code passes the tests.

**Comment by daisieh** [comment]
@dleehr, what is the test for this pr?

**Comment by dleehr** [comment]
Testing steps
1. Make sure there's a journal submission XML file with `<Publication_DOI>` tag in your **/opt/dryad/submission/journalMetadata** dir. You can add it to an existing file for test-review
2. Begin an in-review submission, using the manuscript number that matches **1.**
3. Verify that the Publication DOI from the XML file is read and populated on the form under **DOI**.

**Comment by daisieh** [comment]
Ack, sorry I didn't get to this sooner! I tested it and it looks fine. Merging.

**Pull request merged**
