### PR TITLE
Pub updater fixes

### PR DESCRIPTION
**Pull request by daisieh**
Fixes https://trello.com/c/IJ3y4TV3/139-remove-dryad-citationinprogress-field and https://trello.com/c/6NQfjNJt/484-send-email-notifications-only-when-article-related-metadata-has-changed

### CODE REVIEW

**Comment by daisieh** [comment]
Run this on a VM.

To test, I recommend doing the following: find an item that is in the archive that will match with the  APU, like item_id = 166913. 
- Go to that item's metadata and remove its dc.identifier.citation and dryad.citationInProgress.
- Run the APU: http://localhost:9999/publication-updater/retrieve?1471-2148
- The item's metadata should now have a citation and citationInProgress=true, along with a timestamped APU provenance.
- Make a change to the citation text. If you run the APU again, it should change the citation back and add provenance.
- Make a change to the citation text again, and this time set citationInProgress to false. If you run the APU now, it should leave the change alone and not add a provenance.
- Delete the citationInProgress metadata field. If you run the APU now, it should leave the citation alone and not add a provenance.

**Comment by ryscher** [comment]
Code looks ok.

Tested on dev -- It looks like the citation is always updated, and citationInProgress is always set to true, no matter what value I give citationInProgress, or whether it is deleted.

**Comment by daisieh** [comment]
On my VM, that item was archived. It needs to be archived before you can test it.

**Comment by ryscher** [comment]
Yes, I'm noticing that item is messed up on dev... trying to find a new item that works.

**Comment by ryscher** [comment]
Ok, finally verified on dev using a fresh copy of the production database.

**Pull request merged**
