### PR TITLE
Disable Java-based timer for journal-submit

### PR DESCRIPTION
**Pull request by daisieh**
It’ll be easier and less error-prone to set this using curls and crontab.

### CODE REVIEW

**Comment by ryscher** [comment]
This change is fine. I don't believe we've ever used the timer. Though why comment it out instead of removing it? And if this code is being removed, we should remove the config values from the appropriate config files.

**Comment by daisieh** [comment]
We always use the timer; the recent addition of the cronjob was the first time we've done that instead of the timer.

I guess I couldn't decide if we wanted to remove the feature entirely, or just disable it for now. Opinions?

**Comment by ryscher** [comment]
I prefer the cron solution. It's much easier to modify the settings.

**Comment by ryscher** [comment]
Looks good. Tested on vm.

**Pull request merged**
