### PR TITLE
Review links

### PR DESCRIPTION
**Pull request by daisieh**
Fixes https://trello.com/c/BhuF2rWL/615-files-in-packages-in-review-cant-be-accessed-downloaded-if-youre-not-logged-in

### CODE REVIEW

**Comment by daisieh** [comment]
To test, create a package that is supposed to be in review (perhaps using an msid from a submitted manuscript) and then construct a reviewer URL. You should be able to download the files as well as view file details.

**Comment by ryscher** [comment]
Does this work without the addMetatata step? That UUID is the old way we were keeping the review pages secure, with a real token that was more secure, but more difficult for the journals to track. We switched to using the DOI instead of the full token, which I assume was the reason that line was originally removed.

**Comment by daisieh** [comment]
No, that was actually removed by accident in #1412.

**Comment by ryscher** [comment]
Looks good, tests ok on VM.

**Pull request merged**
