### PR TITLE
Complementary: setFullName to empty string if value is null

### PR DESCRIPTION
**Pull request by daisieh**

### CODE REVIEW

**Comment by ryscher** [comment]
I'm conflicted about this... should we allow a concept to have a blank name (whether null or empty string)? Or should we throw an exception and force a name to exist? What is the meaning of a concept without a name?

**Comment by daisieh** [comment]
I agree that it's problematic. I'll look into how difficult it would be to kick the error back.

**Comment by daisieh** [comment]
If one were to create a concept through the "Manage Journal Settings" GUI, one could easily forget to add the metadata. It seems safest to make sure that null pointers don't get thrown.

**Comment by ryscher** [comment]
ok, that makes sense.

**Pull request merged**
