### PR TITLE
Content/usability and membership pages updates

### PR DESCRIPTION
**Pull request by rnathanday**
Incorporates changes made for:

 * Trello "Update membership info on website to reflect 3 tiers" (Trello card #313, rnathanday:trello-313), and
 * Content, navigation & usability updates (datadryad/dryad-repo PR #873, from elizabethdryad:content-usability)

### CODE REVIEW

**Comment by daisieh** [comment]
@rnathanday, are there particular test cases you want me to verify?

**Comment by ghost** [comment]
@daisieh a lot of the changes here are markup, but looking through the code I did neglect to add Selenium coverage for the Javascript code that changed. I will assign myself the PR to add those, then assign back once they have been added.

**Comment by daisieh** [comment]
#### Code Review Checklist
- [x] Read through the code to ensure it is:
- [x] Legible
- [x] Well-commented
- [x] Free of any "code smells"
- [ ] Ensure the associated documentation is up to date.
- [x] Compile it on your local machine and test the new functionality.
- [x] Verify that the change is accompanied by adequate testing code. Verify that the code passes the tests.

I built it on a VM and looked around and clicked the clicky boxes: everything seems to work as it should, as far as I can tell. 

I don't think there's any doc associated with it. I'm waiting on @rnathanday for Selenium tests, but from a code integrity perspective, it looks good.

**Comment by ghost** [comment]
I have added three Selenium test classes for the JS updates in this PR (and an update to the Selenium pom.xml file):

```
selenium/src/test/java/PagesMembershipOverviewTest.java 
selenium/src/test/java/PagesPaymentPlanComparisonTool.java 
selenium/src/test/java/PagesPaymentTest.java 
```

These tests can be run using this command from the selenium directory:

```
~/dryad-repo/selenium $ mvn package -DseleniumTestURL="http://192.168.111.223:9999" -Dtest=Pages*
```

The expected results from the test run are:

```
Results :
Tests run: 10, Failures: 0, Errors: 0, Skipped: 2
```

The skipped tests are from `@Ignore` ing two non-test classes.

The tests also pass on vagrant using the `runtest_headless.sh` script:

```
~/dryad-repo/selenium $ ./runtest_headless.sh 'Pages*'
```

**Comment by daisieh** [comment]
All right, it works fine! Merging.

**Pull request merged**
